# Overview of basic algorithms with sklearn

- [sklearn.preprocessing.MaxAbsScaler](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MaxAbsScaler.html#sklearn.preprocessing.MaxAbsScaler)
- [sklearn.preprocessing.MinMaxScaler](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MinMaxScaler.html#sklearn.preprocessing.MinMaxScaler)
- [sklearn.preprocessing.RobustScaler](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.RobustScaler.html#sklearn.preprocessing.RobustScaler)
- [sklearn.preprocessing.StandardScaler](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html#sklearn.preprocessing.StandardScaler)

# [MaxAbsScaler](https://stackoverflow.com/questions/58372209/can-someone-explain-maxabsscaler-in-scikit-learn)

In [0]:
from sklearn.preprocessing import MaxAbsScaler
import numpy as np

## In documentation

In [6]:
X = [[ 1., -4.,  2.],
     [ 2.,  0.,  0.],
     [ 0.,  1., -1.]]

transformer = MaxAbsScaler().fit(X)
print(transformer)
transformer.transform(X)

MaxAbsScaler(copy=True)


array([[ 0.5 , -1.  ,  1.  ],
       [ 1.  ,  0.  ,  0.  ],
       [ 0.  ,  0.25, -0.5 ]])

## Explanation

In [10]:
np.max(abs(np.array(X)), axis=0)

array([2., 4., 2.])

In [11]:
np.array(X) / np.max(abs(np.array(X)), axis=0)

array([[ 0.5 , -1.  ,  1.  ],
       [ 1.  ,  0.  ,  0.  ],
       [ 0.  ,  0.25, -0.5 ]])

# [MinMaxScaler](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MinMaxScaler.html#sklearn.preprocessing.MinMaxScaler)

## In documentation

In [0]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

In [22]:
data = np.array([[ 1., -4.,  2.],
                 [ 2.,  0.,  0.],
                 [ 0.,  1., -1.]])
scaler = MinMaxScaler()
print(scaler.fit(data))
print(scaler.transform(data))

MinMaxScaler(copy=True, feature_range=(0, 1))
[[0.5        0.         1.        ]
 [1.         0.8        0.33333333]
 [0.         1.         0.        ]]


## Explanation

In [23]:
(data - np.min(data, axis=0)) / (np.max(data, axis=0) - np.min(data, axis=0)) 

array([[0.5       , 0.        , 1.        ],
       [1.        , 0.8       , 0.33333333],
       [0.        , 1.        , 0.        ]])

# [RobustScaler](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.RobustScaler.html#sklearn.preprocessing.RobustScaler)

## In documentation

In [0]:
from sklearn.preprocessing import RobustScaler
import numpy as np

In [42]:
X  = np.array([[ 1., -2.,  2.],
              [ -2.,  1.,  3.],
              [ 4.,  1., -2.]])
transformer = RobustScaler().fit(X)
print(transformer)
transformer.transform(X)

RobustScaler(copy=True, quantile_range=(25.0, 75.0), with_centering=True,
             with_scaling=True)


array([[ 0. , -2. ,  0. ],
       [-1. ,  0. ,  0.4],
       [ 1. ,  0. , -1.6]])

## Explanation

In [51]:
(X - np.quantile(X, 0.5, axis=0)) / (np.quantile(X, 0.75, axis=0) - np.quantile(X, 0.25, axis=0))

array([[ 0. , -2. ,  0. ],
       [-1. ,  0. ,  0.4],
       [ 1. ,  0. , -1.6]])

```
 (x - Q2) / (Q3 - Q1)
```

# [Normalizer](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.Normalizer.html#sklearn.preprocessing.Normalizer)

## In documents

In [0]:
from sklearn.preprocessing import Normalizer
import numpy as np

In [53]:
X = np.array([[4, 1, 2, 2],
             [1, 3, 9, 3],
             [5, 7, 5, 1]])
transformer = Normalizer().fit(X)  # fit does nothing.
print(transformer)
transformer.transform(X)

Normalizer(copy=True, norm='l2')


array([[0.8, 0.2, 0.4, 0.4],
       [0.1, 0.3, 0.9, 0.3],
       [0.5, 0.7, 0.5, 0.1]])

## Explanation

Xi / sqrt(sum of all squares of that row)

In [69]:
(X.T / (np.sum(np.power(X, 2), axis=1))**0.5).T

array([[0.8, 0.2, 0.4, 0.4],
       [0.1, 0.3, 0.9, 0.3],
       [0.5, 0.7, 0.5, 0.1]])

# [StandardScaler](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html#sklearn.preprocessing.StandardScaler)

## In documents

In [0]:
from sklearn.preprocessing import StandardScaler
import numpy as np

In [71]:
X = np.array([[4, 1, 2, 2],
             [1, 3, 9, 3],
             [5, 7, 5, 1]])
scaler = StandardScaler()  # fit does nothing.
print(scaler.fit(X))
print(scaler.mean_)
scaler.transform(X)

StandardScaler(copy=True, with_mean=True, with_std=True)
[3.33333333 3.66666667 5.33333333 2.        ]


array([[ 0.39223227, -1.06904497, -1.16247639,  0.        ],
       [-1.37281295, -0.26726124,  1.27872403,  1.22474487],
       [ 0.98058068,  1.33630621, -0.11624764, -1.22474487]])

## Explanation

(Xi - Xmean) / (standard Deviation of that feature)

In [89]:
(X - np.mean(X, axis=0)) / np.std(X, axis=0)

array([[ 0.39223227, -1.06904497, -1.16247639,  0.        ],
       [-1.37281295, -0.26726124,  1.27872403,  1.22474487],
       [ 0.98058068,  1.33630621, -0.11624764, -1.22474487]])

# Sourses:

- https://benalexkeen.com/feature-scaling-with-scikit-learn/
- https://scikit-learn.org/stable/modules/classes.html?highlight=preprocessing#module-sklearn.preprocessing
- https://stackoverflow.com/search
- https://www.youtube.com/watch?v=7EbgRHzthWA&list=LLqKuhxjl9Kf2A-yDbcyyiIQ&index=2&t=33s
- https://www.youtube.com/watch?v=cRdPhr1-Srw